"use strict";
exports.__esModule = true;
var express_1 = require("express");
var admin_router_1 = require("./api/admin.router");
var auth_router_1 = require("./api/auth.router");
var lecture_router_1 = require("./api/lecture.router");
var quiz_router_1 = require("./api/quiz.router");
var user_router_1 = require("./api/user.router");
var auth_1 = require("../middleware/auth");
var course_router_1 = require("./api/course.router");
var module_router_1 = require("./api/module.router");
var router = express_1.Router();
router.use(auth_1["default"]);
router.use("/admin", admin_router_1["default"]);
router.use("/api/auth", auth_router_1["default"]);
router.use("/api/user", user_router_1["default"]);
router.use("/api/lecture", lecture_router_1["default"]);
router.use("/api/curriculum/:curriculumId/lecture", lecture_router_1["default"]);
router.use("/api/curriculum/:curriculumId/module", module_router_1["default"]);
router.use("/api/quiz", quiz_router_1["default"]);
router.use("/api/lecture/:lectureId/quiz", quiz_router_1["default"]);
router.use("/api/course", course_router_1["default"]);
router.use("/api/module", module_router_1["default"]);
exports["default"] = router;
